// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9aBeg0U9bepf9xb9xH3ZUgfFK8kAnwy4',
    appId: '1:952033006305:web:5560ff932b774d50785da0',
    messagingSenderId: '952033006305',
    projectId: 'rosheta-e1fa9',
    authDomain: 'rosheta-e1fa9.firebaseapp.com',
    storageBucket: 'rosheta-e1fa9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJydpvMvJ5MwT6w9WOMHvm9ISuObI9B_Q',
    appId: '1:952033006305:android:c07b68756fd6fefb785da0',
    messagingSenderId: '952033006305',
    projectId: 'rosheta-e1fa9',
    storageBucket: 'rosheta-e1fa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBes9hlFmhV3DN4wW7rtGknjRYnPP2F120',
    appId: '1:952033006305:ios:415de6fcadd22f49785da0',
    messagingSenderId: '952033006305',
    projectId: 'rosheta-e1fa9',
    storageBucket: 'rosheta-e1fa9.firebasestorage.app',
    iosBundleId: 'com.example.roshetta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9aBeg0U9bepf9xb9xH3ZUgfFK8kAnwy4',
    appId: '1:952033006305:web:831f68be0cfb86ea785da0',
    messagingSenderId: '952033006305',
    projectId: 'rosheta-e1fa9',
    authDomain: 'rosheta-e1fa9.firebaseapp.com',
    storageBucket: 'rosheta-e1fa9.firebasestorage.app',
  );
}
